export default {
  CHANGE_LAYER: 'CHANGE_LAYER',
  RECEIVE_POLYGONS: 'RECEIVE_POLYGONS',
  ADD_POLYGON: 'ADD_POLYGON',
  CREATE_NEW_POLYGON: 'CREATE_NEW_POLYGON',
  SET_POLYGON_TITLE: 'SET_POLYGON_TITLE',
  ADD_NEW_POLYGON_POINT: 'ADD_NEW_POLYGON_POINT',
  SAVE_NEW_POLYGON: 'SAVE_NEW_POLYGON'
}